// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as SnippetEditor from "./SnippetEditor.bs.mjs";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";
import * as Colors from "@mui/material/colors";
import * as Styles from "@mui/material/styles";

function theme(outerTheme) {
  var newrecord = Caml_obj.obj_dup(outerTheme);
  return Styles.createTheme((newrecord.typography = {
                fontSize: 16.0
              }, newrecord.palette = {
                primary: {
                  main: Colors.pink[500]
                },
                secondary: {
                  main: "#9c27b0"
                }
              }, newrecord));
}

var body = document.querySelector("body");

if (!(body == null)) {
  Client.createRoot(body).render(JsxRuntime.jsx(Styles.ThemeProvider, {
            children: JsxRuntime.jsx(SnippetEditor.make, {}),
            theme: theme
          }));
}

export {
  theme ,
}
/* body Not a pure module */
