// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function Popup(props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  var onIncrement = function (_event) {
    Curry._1(setCount, (function (_count) {
            return _count + 1 | 0;
          }));
  };
  return React.createElement("div", undefined, React.createElement("button", {
                  onClick: onIncrement
                }, "Add"), String(match[0]));
}

var make = Popup;

export {
  make ,
}
/* react Not a pure module */
