// Generated by ReScript, PLEASE EDIT WITH CARE


function prepare(param) {
  (((function() {
    const el = document.querySelector("ytcp-thumbnail-uploader")
    setTimeout(() => {
        el.onFileDrop
    console.log('prep me', el, Object.keys(el))

    }, 3000)


  })()));
}

var onload = (function (reader, cb) {
        setTimeout(() => {
            const el = document.querySelector("ytcp-thumbnail-uploader")
            console.log({el, x: Function.prototype.toString.call(el.startTransfer)})


            const transfer = el["transfer"]
            const file = transfer["blob_"];
            reader.onload = function (e) {
                cb(e.target.result);
            }
            if (file) {
                reader.readAsDataURL(file)
            }
        }, 1000)
    });

function fileToDataUrl($$continue) {
  var reader = new FileReader();
  onload(reader, $$continue);
}

export {
  prepare ,
  onload ,
  fileToDataUrl ,
}
/* No side effect */
