// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Schema from "../Data/Schema.bs.mjs";

function useWhatever(name) {
  var match = React.useState(function () {
        return [
                [],
                undefined
              ];
      });
  var setState = match[1];
  React.useEffect((function () {
          var port = chrome.runtime.connect({
                name: name
              });
          console.log("DescriptionSnippet.hook called");
          var onMessageListener = function (param) {
            var tag = param.tag;
            var payload = param.payload;
            if (tag === "init") {
              console.log("HOOKS: snippets", payload);
              var snippets = payload.map(Schema.DescriptionSnippet.dateFix);
              setState(function (param) {
                    return [
                            snippets,
                            port
                          ];
                  });
            } else {
              throw {
                    RE_EXN_ID: "Match_failure",
                    _1: [
                      "Hooks.res",
                      9,
                      8
                    ],
                    Error: new Error()
                  };
            }
            console.log("app chrome port inbound", tag);
          };
          port.onMessage.addListener(onMessageListener);
          return (function () {
                    console.log("cleanup hook");
                    port.disconnect();
                  });
        }), []);
  return match[0];
}

var DescriptionSnippet = {
  useWhatever: useWhatever
};

export {
  DescriptionSnippet ,
}
/* react Not a pure module */
