// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Schema from "../Data/Schema.bs.mjs";

function useWhatever(name) {
  var match = React.useState(function () {
        return [
                [],
                undefined
              ];
      });
  var setState = match[1];
  React.useEffect((function () {
          var port = chrome.runtime.connect({
                name: name
              });
          var onMessageListener = function (tag) {
            var snippets = tag._0.map(Schema.DescriptionSnippet.dateFix);
            setState(function (param) {
                  return [
                          snippets,
                          port
                        ];
                });
            console.log("app chrome port inbound", tag);
          };
          port.onMessage.addListener(onMessageListener);
          return (function () {
                    port.disconnect();
                  });
        }), []);
  return match[0];
}

var DescriptionSnippet = {
  useWhatever: useWhatever
};

export {
  DescriptionSnippet ,
}
/* react Not a pure module */
