// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Id from "rescript/lib/es6/belt_Id.js";
import * as Belt_Map from "rescript/lib/es6/belt_Map.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.mjs";
import * as TitleChecker from "./Widget/TitleChecker.bs.mjs";
import * as Client from "react-dom/client";

var observerConfig = {
  attributes: false,
  childList: true,
  subtree: true
};

var $$document = window.document;

var cmp = Caml_obj.compare;

var IntCmp = Belt_Id.MakeComparable({
      cmp: cmp
    });

var m = Belt_Map.make(IntCmp);

var dummy = $$document.createElement("div");

var documentTitle_ = $$document.querySelector("title");

var documentTitle_$1 = (documentTitle_ == null) ? undefined : Caml_option.some(documentTitle_);

var documentTitle = Belt_Option.getWithDefault(documentTitle_$1, dummy);

function update(state, action) {
  if (typeof action !== "object") {
    return state;
  }
  if (action.TAG !== "AddWidgets") {
    return {
            currentPage: action._0,
            widgetContainers: state.widgetContainers
          };
  }
  var ws = Belt_Map.merge(state.widgetContainers, action._0, (function (key, maybeA, maybeB) {
          return maybeB;
        }));
  return {
          currentPage: state.currentPage,
          widgetContainers: ws
        };
}

var app = Core__Option.map(Caml_option.nullable_to_opt($$document.querySelector("title")), (function (titleEl) {
        var App = function (props) {
          var initialState = {
            currentPage: "Other",
            widgetContainers: m
          };
          var match = React.useReducer(update, initialState);
          var onMessageListener = function (port) {
            console.log("App is listening for Chrome Messages", port);
          };
          var port = chrome.runtime.connect({
                name: "yt-widgets-content"
              });
          port.onMessage.addListener(onMessageListener);
          var titleWatcher = function (mutationList, obsever) {
            console.log("body");
          };
          React.useEffect((function (param) {
                  var titleObserver = new MutationObserver(titleWatcher);
                  titleObserver.observe(titleEl, observerConfig);
                  return (function (param) {
                            titleObserver.disconnect();
                          });
                }), []);
          var widgets = Belt_Map.valuesToArray(match[0].widgetContainers);
          console.log("widigies", widgets);
          return [React.createElement(TitleChecker.make, {})];
        };
        var root = Client.createRoot(dummy);
        root.render(React.createElement(App, {}));
      }));

export {
  observerConfig ,
  $$document ,
  IntCmp ,
  m ,
  dummy ,
  documentTitle_$1 as documentTitle_,
  documentTitle ,
  update ,
  app ,
}
/* document Not a pure module */
