// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TitleChecker from "./Widget/TitleChecker.bs.mjs";
import * as Client from "react-dom/client";

function App$App(props) {
  console.log("Hello ReScript");
  return React.createElement("div", undefined, React.createElement(TitleChecker.make, {
                  text: "Video Title Checker goes here"
                }));
}

var App = {
  make: App$App
};

function onMessageListener(port) {
  console.log(port);
  var dummy = window.document.createElement("div");
  var root = Client.createRoot(dummy);
  root.render(React.createElement(App$App, {}));
}

var port = chrome.runtime.connect({
      name: "yt-widgets-content"
    });

port.onMessage.addListener(onMessageListener);

export {
  App ,
  onMessageListener ,
  port ,
}
/* port Not a pure module */
