// Generated by ReScript, PLEASE EDIT WITH CARE


var Port = {};

var OnConnect = {};

var OnMessage = {};

var Runtime = {
  Port: Port,
  OnConnect: OnConnect,
  OnMessage: OnMessage
};

export {
  Runtime ,
}
/* No side effect */
