// Generated by ReScript, PLEASE EDIT WITH CARE


var OnDisconnect = {};

var Port = {
  OnDisconnect: OnDisconnect
};

var OnConnect = {};

var OnMessage = {};

var Runtime = {
  Port: Port,
  OnConnect: OnConnect,
  OnMessage: OnMessage
};

var $$Storage = {};

export {
  Runtime ,
  $$Storage ,
}
/* No side effect */
