// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Client from "react-dom/client";

function createInjectElement(param) {
  return document.createElement("div");
}

function mount(target, widget) {
  var wrapper = document.createElement("div");
  var root = Client.createRoot(wrapper);
  root.render(widget);
  return target.appendChild(wrapper);
}

var Inject = {
  createInjectElement: createInjectElement,
  mount: mount
};

export {
  Inject ,
}
/* react-dom/client Not a pure module */
