// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

var Description = {};

var EditNote = {};

var Less = {};

var More = {};

var Expand = {
  Less: Less,
  More: More
};

var Input = {};

var NoteAdd = {};

var Icon = {
  Description: Description,
  EditNote: EditNote,
  Expand: Expand,
  Input: Input,
  NoteAdd: NoteAdd
};

function pause() {
  return new Promise((function (resolve, reject) {
                setTimeout((function () {
                        resolve(undefined);
                      }), 500);
              }));
}

var TestError = /* @__PURE__ */Caml_exceptions.create("Ui.TestError");

async function queryDom(maybeAncestor, selector, n) {
  if (n < 0) {
    return Promise.reject({
                RE_EXN_ID: TestError,
                _1: "Not Found"
              });
  }
  await pause();
  var maybeEl = Belt_Option.mapWithDefault(maybeAncestor, Caml_option.nullable_to_opt(document.querySelector(selector)), (function (dialog) {
          return Caml_option.nullable_to_opt(dialog.querySelector(selector));
        }));
  if (maybeEl !== undefined) {
    return Promise.resolve(Caml_option.valFromOption(maybeEl));
  } else {
    return await queryDom(maybeAncestor, selector, n - 1 | 0);
  }
}

export {
  Icon ,
  pause ,
  TestError ,
  queryDom ,
}
/* No side effect */
