// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var ytSelector = "ytcp-video-title";

function make(props) {
  var maybeVideoTitleEl = document.querySelector(ytSelector);
  React.createElement("div", {
        id: "TitleChecker.view"
      }, props.text);
  var moConfig = {
    attributes: false,
    childList: true,
    subtree: true
  };
  var watcher = function (mutationList, observer) {
    console.log(mutationList);
  };
  var observer = new MutationObserver(watcher);
  return Belt_Option.mapWithDefault((maybeVideoTitleEl == null) ? undefined : Caml_option.some(maybeVideoTitleEl), React.createElement(React.Fragment, undefined), (function (videoTitleEl) {
                observer.observe(videoTitleEl, moConfig);
                return React.createElement(React.Fragment, undefined);
              }));
}

export {
  ytSelector ,
  make ,
}
/* react Not a pure module */
