// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as ReactDom from "react-dom";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ReactQuery from "@rescriptbr/react-query/src/ReactQuery.bs.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as ReactQuery$1 from "@tanstack/react-query";

var observerConfig = {
  attributes: false,
  childList: true,
  subtree: true
};

var viewOverLimit = React.createElement("div", {
      id: "TitleChecker.viewOverLimit",
      style: {
        color: "#dc3545",
        fontSize: "12px",
        padding: "0.2rem 1rem",
        textAlign: "right"
      }
    }, "Your title is a little long there, pal...");

function TitleChecker$TitleChecker(props) {
  var maybeVideoTitleEl = document.querySelector("ytcp-video-title");
  var maybeVideoTitleInput = Belt_Option.flatMap((maybeVideoTitleEl == null) ? undefined : Caml_option.some(maybeVideoTitleEl), (function (el) {
          return Caml_option.nullable_to_opt(el.querySelector("ytcp-social-suggestion-input"));
        }));
  var initialState = Belt_Option.mapWithDefault(maybeVideoTitleInput, {
        TAG: /* UnderLimit */1,
        _0: 0.0
      }, (function (videoTitleEl) {
          var len = videoTitleEl.innerText.length;
          if (len > 60.0) {
            return {
                    TAG: /* OverLimit */0,
                    _0: len
                  };
          } else {
            return {
                    TAG: /* UnderLimit */1,
                    _0: len
                  };
          }
        }));
  var match = React.useState(function () {
        return initialState;
      });
  var setState = match[1];
  var state = match[0];
  var viewProgress = function (len) {
    var w_ = len / 60.0 * 100.0;
    var w = Math.min(w_, 100.0);
    var width = String(w) + "%";
    var backgroundColor = len > 60.0 ? "red" : (
        len > 42.0 ? "yellow" : "green"
      );
    return React.createElement("div", {
                id: "TitleChecker.progress"
              }, React.createElement("div", {
                    style: {
                      backgroundColor: backgroundColor,
                      height: "2px",
                      width: width
                    }
                  }));
  };
  var children;
  children = state.TAG === /* OverLimit */0 ? [
      viewProgress(state._0),
      viewOverLimit
    ] : [viewProgress(state._0)];
  var watcher = function (mutationList, observer) {
    var textboxLen = Belt_Option.mapWithDefault(Belt_Option.map(Belt_Option.map(Belt_Array.get(mutationList, 0), (function (mutation) {
                    return mutation.target;
                  })), (function (el) {
                return el.innerText;
              })), 0.0, (function (text) {
            return text.length;
          }));
    if (textboxLen > 60.0) {
      return Curry._1(setState, (function (param) {
                    return {
                            TAG: /* OverLimit */0,
                            _0: textboxLen
                          };
                  }));
    } else {
      return Curry._1(setState, (function (param) {
                    return {
                            TAG: /* UnderLimit */1,
                            _0: textboxLen
                          };
                  }));
    }
  };
  var observer = new MutationObserver(watcher);
  React.useEffect(function () {
        return (function (param) {
                  observer.disconnect();
                });
      });
  var asyncTimeout = function (param) {
    return new Promise((function (resolve, reject) {
                  setTimeout((function (param) {
                          resolve(undefined);
                        }), 1000);
                }));
  };
  var queryDomHelp = async function (n) {
    console.log("waiting...");
    await asyncTimeout(undefined);
    console.log("querying...");
    var maybeVideoTitleEl = document.querySelector("ytcp-video-title");
    if (maybeVideoTitleEl == null) {
      return await queryDomHelp(n - 1 | 0);
    } else {
      return Promise.resolve(maybeVideoTitleEl);
    }
  };
  var queryDom = function (param) {
    return Js_promise2.then(queryDomHelp(3), (function (el) {
                  return el;
                }));
  };
  var queryResult = ReactQuery$1.useQuery({
        queryKey: ["todos"],
        queryFn: queryDom,
        refetchOnMount: Caml_option.some(ReactQuery.refetchOnMount({
                  NAME: "bool",
                  VAL: true
                })),
        refetchOnWindowFocus: Caml_option.some(ReactQuery.refetchOnWindowFocus({
                  NAME: "bool",
                  VAL: false
                }))
      });
  console.log("query", queryResult);
  var tmp;
  if (queryResult.isLoading) {
    tmp = "Loading...";
  } else if (queryResult.isError) {
    tmp = "Unexpected error...";
  } else {
    var videoTitleEl = queryResult.data;
    if (videoTitleEl !== undefined) {
      var videoTitleEl$1 = Caml_option.valFromOption(videoTitleEl);
      var maybeVideoTitleInput$1 = videoTitleEl$1.querySelector("ytcp-social-suggestion-input");
      if (maybeVideoTitleInput$1 == null) {
        tmp = React.createElement(React.Fragment, undefined);
      } else {
        observer.observe(maybeVideoTitleInput$1, observerConfig);
        tmp = ReactDom.createPortal(children, videoTitleEl$1);
      }
    } else {
      tmp = "Unexpected error...";
    }
  }
  return React.createElement("div", undefined, tmp);
}

var TitleChecker = {
  viewOverLimit: viewOverLimit,
  make: TitleChecker$TitleChecker
};

var client = new ReactQuery$1.QueryClient();

function TitleChecker$1(props) {
  console.log("title check me pls");
  return React.createElement(ReactQuery$1.QueryClientProvider, {
              client: client,
              children: React.createElement(TitleChecker$TitleChecker, {})
            });
}

var make = TitleChecker$1;

export {
  observerConfig ,
  TitleChecker ,
  client ,
  make ,
}
/* viewOverLimit Not a pure module */
