// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Inject from "../Content/Inject.bs.mjs";

function Counter$Counter(props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  var count = match[0];
  console.log(count);
  var onIncrement = function (_event) {
    Curry._1(setCount, (function (_count) {
            return _count + 1 | 0;
          }));
  };
  return React.createElement("div", {
              className: "yt-widgets-Counter"
            }, React.createElement("button", {
                  onClick: onIncrement
                }, "Add"), String(count));
}

var Counter = {
  make: Counter$Counter
};

function Counter$1(props) {
  var counter = React.createElement(Counter$Counter, {});
  var rootElement = document.querySelector("ytcd-channel-facts-item");
  if (rootElement == null) {
    return counter;
  } else {
    Inject.Inject.mount(rootElement, counter);
    return counter;
  }
}

var make = Counter$1;

export {
  Counter ,
  make ,
}
/* react Not a pure module */
